
<?php
$titre='Les informations du petit Lachal Illustré !';
include('menu.php');
?>
<h2>Informations en temps réel de l'actualité du site :</h2>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :(07-2008)</em> Réecriture globale du code, mise en plance d'une tamporisation. Ajout des catégories. Utilisation des balises définitions...et plus encore !</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :(02-2008)</em> Comment marche le moteur phonétique ? Très simple ! Il suffit de rajouter juste après <a href="https://lachal.neamar.fr">https://lachal.neamar.fr</a> le mot que vous recherchez. Un exemple ? Vous recherchez thuriféraire, vous appuyez donc sur F6, puis vous marquez thuriféraire <strong> de la façon que vous voulez !</strong> à la suite de l'URL : https://lachal.neamar.fr/turifferrere.</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :(02-2008)</em> Et bien, il n'y a pas à dire, mais les modifs s'enchainent et ne se ressemblent pas ! Déjà, une page est dédiée à chaque mot. Ensuite, j'ai mis en place un moteur phonétique : si vous n'êtes pas sûr de la prononciation d'un mot, il suffit de le marquer 'au feeling'. Un exemple ? Marchmalo (au lieu de marshmallow). Et j'ai aussi refait le parser de mots dans les exemples.<br />Et pendant que j'y étais, j'ai même refait le formulaire d'ajout, beaucoup plus transparent maintenant.</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS : (01-2008)</em> Ce n'est qu'un au revoir... eh oui, c'est dorénavant fini, nous n'aurons plus nos provisions hebdomadaires de mots... il nous en reste encore une trentaine, mais après ?<br />Eh bien, nous pourrions bouger vers d'autres projets (comme <a href="http://ccds.neamar.fr">ce jeu </a> codé par votre serviteur), ou simplement améliorer ce site de façon à dépanner les internautes à la recherche de mots particuliers. Et on pourrait même faire les deux en même temps !</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS : (12-2007)</em> Allez hop ! On change d'hébergeur ! La stabilité du serveur de l'INSA étant assez capricante, autant se greffer sur un site qui marche bien ! Bon, pour le lecteur, il n'y a pas grand-chose qui change, à part la barre de menu plus intégrée.</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS : (12-2007)</em> En me baladant sur le net, j'ai trouvé ça... comment ne pas penser à M. Lachal ? <img src="http://www.novaksblog.com/pictures/stumble_on_sunday_2nd_part/just_quit_it.jpg" alt="Just Quit It !"/></p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS : (11-2007)</em> Re-Tadam ! Les histoires de Mickey vous ont plu ? Allez vous rafraîchir la mémoire en regardant quelques photos prises sur le vif par d'éminents paparazzis. C'est par ici ! EDIT : Lien supprimé...</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :  (11-2007)</em> Tadam ! Vous commencez à trouver ce dictionnaire inintéressant ? Vous avez tort, mais bon... allez, on vous offre une page fourmillant d'expressions idiomatiques, et d'histoires de Toto... <a href="expressions.php">C'est par ici !</a></p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :  (11-2007)</em> Un bug d'Internet Explorer empêchait d'utiliser l'index en bas à droite... c'est maintenant réparé : il suffit de cliquer sur un mot pour y aller !</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :  (11-2007)</em> Un nouveau design en cours d'implantation, une page qui recensera les expressions idiomatiques, 50 mots de retard... ici, on  ne chôme pas... en maths non plus d'ailleurs. Mais pour vous lecteurs, ce n'est que du plaisir... Just enjoy it !</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :  (11-2007)</em> Ultra posse nemo obligatur : eh oui, il y avait des fautes d'orthographe (et il y en a sûrement encore ;-{ ). J'en ai corrigé une bonne quarantaine, mais il en reste sûrement... faites attention en postant ! J'en ai aussi profité pour rajouter quelques exemples, et dépoussiérer certains exemples complètement obsolètes.</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :  (11-2007)</em> Le site a l'honneur d'accueillir un nouvel affidé stipendié : M. Clément P. s'est donc joint à nous et nous aidera désormais à emmagasiner virtuellement tout le savoir dispensé par M. Lachal. Un seul commentaire : Clément, just compute it !</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS : (10-2007)</em> Le site encyclopédique est maintenant équipé d'un flux RSS, pour ne pas rater les dernières nouveautés. Vous le trouverez <a href="rss.php">ici</a></p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS : (10-2007)</em> M. Lachal nous a informés dans un mail très rhétorique de sa bénédiction envers ce site. Bien que les mots cités dans ce mail suffiraient pour multiplier le Q.I. de toute personne (a)normalement constituée par deux, ce mail adressé au trois principaux contributeurs est et restera privé, pour des raisons de fierté personnelle... (un mot du maître !). Seul le premier paragraphe est donc disponible, vous le trouverez comme illustration du mot logorrhée.</p>
<p class="info"><em style="text-decoration:blink;">INFORMATIONS :  (10-2007)</em> Désormais, cliquer sur un mot compliqué dans un exemple vous amènera à la définition de ce mot !</p>
</div>
</body>
</html>
